### ISSUE TITLE
lowdb returns Promise - consider refactor?

### ISSUE THREAD

**Issue by devjmetivier** [wesbos/scrapecity#2]
Hey Wes!

I'm running into this problem where I'm exporting the db before the lowdb Promise has a chance to resolve. I'm not entirely sure this is the best way to mitigate this issue. It might be a perf suck ☹️ Inside of `db.js` I've changed it to wait until the db returns:

```javascript
const adapter = new FileSync('db.json');

export async function initDB() {
  const db = await low(adapter);
  db.defaults({ twitter: [], instagram: [] }).write();
  return db;
}
```

And then when you want to scrape and save to the db I've changed it to:

`index.js`
```javascript
import { initDB } from './lib/db'; // instead of 'db'

initDB().then(async db => {
  app.get('/scrape', async (req, res, next) => {
    // the rest here is the same
});
```

`scraper.js`
```javascript
import { initDB } from './lib/db'; // instead of 'db'

export async function runCron() {
  const [igCount, twCount] = await Promise.all([
    getInstagramCount(),
    getTwitterCount(),
  ]);

  initDB().then(db => {
    // everything else inside is the same with db.get().push().write() calls 😁 
  });
}
```

Is this the best way to go about changing this to work to make sure the lowdb Promise resolves when initializing the db? Permission to make a PR?

I've found issues relating to this from people who have trouble with the examples from lowdb:
* https://github.com/typicode/lowdb/issues/222
* https://github.com/typicode/lowdb/pull/223

**Comment by wesbos** [comment]
Ah - will note this in the next video - good to make it async especially if it's dealing with the filesystem - thanks!

**Comment by anjagusev** [comment]
Thanks @dmetivier I was having the same problem and this really helped me.
